export const CHECK_FIELDS: any[] = [
  {name: 'Order ID', isChecked: false},
  {name: 'Order CBS', isChecked: false},
  {name: 'Order OID', isChecked: false},
  {name: 'Order UTR', isChecked: false},
  {name: 'Total Amount', isChecked: false},
  {name: 'Category', isChecked: false},
  {name: 'Order State', isChecked: false},
  {name: 'Status Desc', isChecked: false},
  {name: 'Debit Account', isChecked: false},
  {name: 'Credit Account', isChecked: false},
  {name: 'Status', isChecked: false},
  {name: 'Txn Mode', isChecked: false},
  {name: 'Payment Initiated At', isChecked: false},
  {name: "Payment Success At", isChecked: false},
  {name: 'Updated Date', isChecked: false},
  {name: 'Inserted Date', isChecked: false},
  {name: 'Notiid', isChecked: false},
];
